# Generated by Django 2.2.1 on 2019-05-27 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True, verbose_name='Date of Birth')),
                ('pesel', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='PESEL')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('work', 'Work'), ('home', 'Home'), ('mobile', 'Mobile')], default='mobile', max_length=30, verbose_name='Role')),
                ('number', models.CharField(max_length=20, verbose_name='Number')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Person', verbose_name='Person')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('work', 'Work'), ('home', 'Home'), ('other', 'Other')], default='home', max_length=30, verbose_name='Role')),
                ('street', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Street')),
                ('house_number', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='House Number')),
                ('apartment', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Apartment')),
                ('post_code', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Post Code')),
                ('city', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Country')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Person', verbose_name='Person')),
            ],
        ),
    ]
