# Generated by Django 2.2.1 on 2019-05-28 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20190528_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='role',
            field=models.CharField(choices=[('work', 'Work'), ('home', 'Home'), ('mobile', 'Mobile'), ('other', 'Other')], default='other', max_length=30, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('work', 'Work'), ('home', 'Home'), ('other', 'Other')], default='other', max_length=30, verbose_name='Role')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Number')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
    ]
