# Generated by Django 2.2.1 on 2019-05-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_person_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pesel',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Type your PESEL number', null=True, verbose_name='PESEL'),
        ),
    ]
