# Generated by Django 2.2.1 on 2019-05-28 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20190528_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), (None, 'Unspecified')], default=None, max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(220)], verbose_name='Height'),
        ),
    ]
