# Generated by Django 2.2.1 on 2019-05-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20190528_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_friend',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Is Friend?'),
        ),
    ]
