# Generated by Django 2.2.1 on 2019-05-28 09:42

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_person_is_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, verbose_name='Date Added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_friend',
            field=models.BooleanField(blank=True, choices=[(True, 'My best friend'), (False, 'Not a friend'), (None, 'Unspecified')], default=None, null=True, verbose_name='Is Friend?'),
        ),
    ]
