# Generated by Django 2.2.1 on 2019-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20190528_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Last Name'),
        ),
    ]
