# Generated by Django 2.2.1 on 2019-05-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20190528_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, to='contact.Person', verbose_name='Friends'),
        ),
    ]
